Issue #LR-515 feat: Added the decryption tool
Sunbird-Lern/sunbird-utils pull request #1156
Opened 2023-05-02 09:20 UTC by AmiableAnil

2023-05-05 05:32 UTC, maheshkumargangula requested changes

2023-05-05 05:32 UTC, maheshkumargangula commented on decryption-tool/README.md
> +# How to run
Please specify the technical requirements to run the tool.
Which version of Python should be installed. Will it work on Windows, Ubuntu, Mac?

2023-05-05 05:32 UTC, maheshkumargangula commented on decryption-tool/decrypt.sh
> +else
Explicitly have a `if else` block for level 4 and else block should print invalid input.

2023-05-05 05:32 UTC, maheshkumargangula commented on decryption-tool/src/utils.py
> +        remove("m1.txt")
Is this statement required?

2023-05-05 07:02 UTC, SanthoshVasabhaktula requested changes

2023-05-05 07:02 UTC, SanthoshVasabhaktula commented on decryption-tool/decrypt.sh
> +if [ "$level" == 3 ]
As suggested above remove the level understanding from the decrypt tool. Make it simple with either taking in an encryption key or pem file

2023-05-12 07:58 UTC, reshmi-nair approved these changes

2023-05-12 07:58 UTC, reshmi-nair approved these changes

2023-05-26 05:38 UTC, reshmi-nair approved these changes

2023-05-26 05:39 UTC, merged